### ISSUE TITLE
adapt simple escrow.sol for NFT / erc721 - 350 $LEX

### ISSUE THREAD

**Issue by Ro5s** [lexDAO/LexCorpus#14]
we have a bare bones escrow contract for locking and releasing erc20 tokens between a depositor (grantor) and recipient. 

NFTs can represent financial assets, other rights, and simple escrow in lexdao syntax would be great.

adapt file: [escrow](https://github.com/lexDAO/LexCorpus/blob/master/contracts/escrow/standard/escrow.sol)

erc721 interface: [file](https://github.com/lexDAO/LexCorpus/blob/master/contracts/standard/token/ERC721/IERC721.sol)

**Comment by Ro5s** [comment]
write docs describing how NFT can represent off-chain asset. I.e, Legal Script

**Comment by georgeroman** [comment]
If still available, I can take this one.

**Comment by Ro5s** [comment]
will return after reorg
