### ISSUE TITLE
Review Requested: LexNFT

### ISSUE THREAD

**Issue by Ro5s** [lexDAO/LexCorpus#2]
We are very close to having a light implementation of ERC-721 token that also tracks some of our 'offer token' patterns from LexToken ERC-20. 

Requesting a review of the basic contract: https://github.com/lexDAO/LexCorpus/blob/master/contracts/token/lextoken/solidity/LexNFTFactory.sol

Bounty: 25 [$LEX](https://etherscan.io/token/0xA5C5C8Af327248c4c2dce810a3d3Cffb8C4F66ab)

**Comment by andy8052** [comment]
Looking at this quickly I think it looks very solid. What would you guys think about breaking out the pure ERC721 logic and then extending it with your custom logic such as `resolver`, `totalSupplyCap` and `transferable`. 

Also, is there a reason for using `init` instead of just a `constructor`?

**Comment by Ro5s** [comment]
Thanks for taking a look :-) ! @andy8052 We use init instead of constructor to implement minimal proxy (eip1167) for deployment of new mintable NFT to save tons on gas. 

Agree that breaking out our governancy and other more custom extensions is solid direction 🚴

Would love to send $LEX your way to recognize this input! What’s a good ethereum address?
